baseURL = 'https://www.joeykleinsorge.com/'
languageCode = 'en-us'
title = 'Joey Kleinsorge'
theme = 'my-hello-friend-ng'
PygmentsCodeFences = true
PygmentsStyle = "monokai"
archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"
buildDrafts  = false
buildFuture  = false
buildExpired = false
canonifyURLs = true
enableRobotsTXT = true
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Joey Kleinsorge"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag      = "tags"
  category = "categories"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"

  # Metadata 
  description = "Joey Kleinsorge"
  keywords = "Joey Kleinsorge"
  images = ""
  homeSubtitle = "Avid lover of automation, code that works and coffee."
  disableReadOtherPosts = false
  EnableThemeToggle = true
  enableSharingButtons = true
  enableGlobalLanguageMenu = false
  customCSS = []
  customJS  = []
  justifyContent = true
  gitUrl = 'https://github.com/JoeyKleinsorge/JoeyKleinsorge.com/commit/'

  [params.footer]
    trademark = true
    rss = true
    copyright = false
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"http://gohugo.io\">Hugo</a>"
    ]

  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
    logoMark     = ">"
    logoText     = "Joey Kleinsorge"
    logoHomeLink = "/"
    logoCursorColor    = "#40a3b8"
    logoCursorAnimate  = "1s"

  [[params.social]]
    name = "email"
    url  = "mailto:joey@kleinsorge.dev"

  [[params.social]]
    name = "github"
    url = "https://github.com/JoeyKleinsorge"

  [[params.social]]
    name = "gitlab"
    url = "https://gitlab.com/joeykleinsorge"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/joeykleinsorge/"


[languages]
  [languages.en]

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about"
  [[menu.main]]
    identifier = "curated"
    name       = "Curated"
    url        = "curated"        
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"
  [[menu.main]]
    identifier = "now"
    name       = "Now"
    url        = "now"
    
[module]
  [[module.mounts]]
    source = "./node_modules/highcharts"
    target = "assets/js/highcharts"
